version: '3'

networks:
  inception: {}

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/cptboy/data/wordpress"
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/cptboy/data/mariadb"

services:
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    networks:
      - inception
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MARIADB_NAME=${MARIADB_NAME}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb
    restart: "on-failure"
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    restart: "on-failure"
